name: Java CI

on:
  push:
    branches:
      - main
      - master
      - ankush2
  pull_request:
    branches:
      - main
      - master
      - ankush2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Install Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Build and test
      - name: Build & Test with Maven
        run: ./mvnw clean package

