name: Java CI

# Trigger on pushes or PRs to main, master, or your feature branch
on:
  push:
    branches:
      - main
      - master
      - ankush2
  pull_request:
    branches:
      - main
      - master
      - ankush2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Build & test with Maven
      - name: Build & Test
        run: ./mvnw clean package

    
